### ISSUE TITLE
Prepare list for next DRS deposits

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#103]
- [x] Get list of Tibetan works which do not have HOLLIS numbers.
- [x] Build a sample set of MARC records using 
`http://purl.bdrc.io/resource/W12827.mrcx` (Elie asked for 2 sec delay between GETs) The list was generated by #103
- [ ] Send these MARC to Corinna
- [ ] Update DRS database with those works, which now have HOLLIS numbers
- [ ] Test some deposits.
- [ ] Write the list of HOLLIS back into eXist (with Chris)

**Comment by jimk-bdrc** [comment]
Tibetan/sanskrit works are !FPL and !FEMC

**Comment by TBRC-TimB** [comment]
> Tibetan/sanskrit works are !FPL and !FEMC

just a clarification here when you say !FPL you mean NOT FPL right?

**Comment by TBRC-TimB** [comment]
Reviving this thread. I'm back in touch with Corinna and she has some feedback on our sample data: 
The problem I mentioned before has not been resolved. Two of the files contain invalid content and just a 404 error instead of a MARC record:

{"status":404,"code":5010,"message":"http://purl.bdrc.io/resource/W16097","link":null,"developerMessage":null}

 

The two files are W16097 and W00KG0615.

 

Also, file W1AC24 is missing a 245 field. This field is mandatory and records without it can't be loaded.

 

Can you change the format of the 001 fields? Currently you have:

 

   <marc:controlfield tag="001">(BDRC)bdr:W00EGS1016181</marc:controlfield>

 

Please change value to just your unique identifier, e.g.: W00EGS1016181

 

Please add fixed field 003 with content: MaCbBDRC

 

Please remove field 035.

 @eroux since these records are generated from calls to buda, i image those changes would need to be made on that end. Some of these are clearly errors in our own data (missing fields and the 404s) and I can filter for that in the future.

**Comment by jimk-bdrc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Next DRS](https://trello.com/c/UqCp4aYg/10-next-drs)

**Comment by TBRC-TimB** [comment]
Next steps: 

Write up an xsl transform that incorporates Corinna's feedback and massages our MARC into something harvard-friendly

Discuss some changed that we might want to make on emission/creation (changes to the Marc Generation Class, creation of a subclass for specific marc variants). These changes aren't necessary at this stage (since the xslt should make everything good for Harvard) but might be a good idea for general use further down the pipe.

**Comment by TBRC-TimB** [comment]
Got a response from Corinna 

This looks good. Two things:

1. The ISBN of the print original should not go in 020 $z. It should go into 776 like so: 776/0_   $cOriginal$z7540932317
2. Can you remove the extraneous space in the pagination? E.g. change "1 online resource (3, 347 pages)" to "1 online resource (3,347 pages)"

Thanks!

@eroux  how possible is it to make these changes easily on our end? I imagine the second one might be tricky since it would involve correcting the actual content of the fields rather than just how they are presented in the marc record.

**Comment by TBRC-TimB** [comment]
We have the go head from corinna to send them the marc records as we generated them. After the break I will get in touch with her again and we can work out an upload process and a rate. and build a list of things that need hollis numbers.

**Comment by jimk-bdrc** [comment]
Completed by #117
